### ISSUE TITLE
Error caught from Recipe Category from HEI and Extended Crafting

### ISSUE THREAD

**Issue by MetaverseRPN** [Nomifactory/ExtendedCrafting#37]
When attempting to view an ultimate crafting table recipe on HEI, the recipe disappears and gives a Nullpointer exception in the console. 
Error traceback is below:
`Error caught from Recipe Category: com.blakebr0.extendedcrafting.compat.jei.tablecrafting.UltimateTableCategory
java.lang.NullPointerException
	at mezz.jei.gui.ingredients.GuiIngredientGroup.set(GuiIngredientGroup.java:114)
	at com.blakebr0.extendedcrafting.compat.jei.tablecrafting.UltimateTableCategory.setRecipe(UltimateTableCategory.java:77)
	at mezz.jei.gui.recipes.RecipeLayout.create(RecipeLayout.java:69)
	at mezz.jei.gui.recipes.RecipeGuiLogic.getRecipeLayouts(RecipeGuiLogic.java:198)
	at mezz.jei.gui.recipes.RecipesGui.updateLayout(RecipesGui.java:492)
	at mezz.jei.gui.recipes.RecipesGui.initGui(RecipesGui.java:173)
	at net.minecraft.client.gui.GuiScreen.setWorldAndResolution(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:1018)
	at mezz.jei.gui.recipes.RecipesGui.open(RecipesGui.java:382)
	at mezz.jei.gui.recipes.RecipesGui.show(RecipesGui.java:408)
	at mezz.jei.input.InputHandler.handleFocusKeybinds(InputHandler.java:277)
	at mezz.jei.input.InputHandler.handleKeyDown(InputHandler.java:235)
	at mezz.jei.input.InputHandler.handleKeyEvent(InputHandler.java:217)
	at mezz.jei.input.InputHandler.onGuiKeyboardEvent(InputHandler.java:78)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_7877_InputHandler_onGuiKeyboardEvent_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:513)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.run(Minecraft.java:9114)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by MetaverseRPN** [comment]
Disregard, this was revealed to be user error.
